
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T16:08:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dc61be109690a1c5a0c7b18072b9759335ae193",
 "version": "1.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
