VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('19')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('48')
MAJOR_VERSION = 0
MINOR_VERSION = 1
PATCH_VERSION = 202212191048
version_date = '2022/12/19 10:48'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
