# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extractor/extractor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65xtractor/extractor.proto\x12\x14\x65xtractor_APIs_proto\"\xab\x01\n\x0b\x46ormRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x11\n\tinputType\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x0e\n\x06\x62\x61se64\x18\x04 \x01(\t\x12\r\n\x05pages\x18\x05 \x01(\x03\x12\x10\n\x08mimeType\x18\x06 \x01(\t\x12\x16\n\x0e\x65xtractionType\x18\x07 \x01(\t\x12\x0f\n\x07rawJson\x18\x08 \x01(\x08\x12\x10\n\x08\x66ileName\x18\t \x01(\t\"\x18\n\x08Response\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\"\xa2\x01\n\nDocRequest\x12\x11\n\tinputType\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06\x62\x61se64\x18\x03 \x01(\t\x12\x10\n\x08mimeType\x18\x04 \x01(\t\x12\x16\n\x0e\x65xtractionType\x18\x05 \x01(\t\x12\x17\n\x0f\x65xtractionHints\x18\x06 \x01(\x08\x12\x0f\n\x07rawJson\x18\x07 \x01(\x08\x12\x10\n\x08\x66ileName\x18\x08 \x01(\t\"\xb2\x01\n\nVinRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x11\n\tinputType\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0e\n\x06\x62\x61se64\x18\x05 \x01(\t\x12\x10\n\x08mimeType\x18\x06 \x01(\t\x12\x16\n\x0e\x65xtractionType\x18\x07 \x01(\t\x12\x0f\n\x07rawJson\x18\x08 \x01(\x08\x12\x15\n\rpreProcessors\x18\t \x03(\t2\x85\x02\n\x13\x45xtractorController\x12T\n\x0f\x46ormRecognition\x12!.extractor_APIs_proto.FormRequest\x1a\x1e.extractor_APIs_proto.Response\x12I\n\x05\x44ocAI\x12 .extractor_APIs_proto.DocRequest\x1a\x1e.extractor_APIs_proto.Response\x12M\n\tVinNumber\x12 .extractor_APIs_proto.VinRequest\x1a\x1e.extractor_APIs_proto.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extractor.extractor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FORMREQUEST._serialized_start=52
  _FORMREQUEST._serialized_end=223
  _RESPONSE._serialized_start=225
  _RESPONSE._serialized_end=249
  _DOCREQUEST._serialized_start=252
  _DOCREQUEST._serialized_end=414
  _VINREQUEST._serialized_start=417
  _VINREQUEST._serialized_end=595
  _EXTRACTORCONTROLLER._serialized_start=598
  _EXTRACTORCONTROLLER._serialized_end=859
# @@protoc_insertion_point(module_scope)
