# allowed deleted edges
allowed_deleted_edges = [
    "HAS_ACTOR_PREFERENCE",
    "HAS_TAG_PREFERENCE",
    "HAS_SUBCATEGORY_PREFERENCE",
    "HAS_ATTRIBUTE1_PREFERENCE",
    "HAS_DIRECTOR_PREFERENCE",
    "HAS_DURATION_PREFERENCE",
    "HAS_TOD_PREFERENCE",
    "HAS_CATEGORY_PREFERENCE",
    "HAS_RATING_PREFERENCE",
    "HAS_MINIBATCH_KMEANS_CLUSTER",
    "HAS_PAYTV_PROVIDER",
    "HAS_TAG",
    "HAS_COUNTRY",
    "HAS_HOMEPAGE",
    "HAS_CONTENT_CORE",
    "HAS_ACTOR",
]
