
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T22:44:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5f04b2161e543c6d69f7d0bf6121eabddceb1c2",
 "version": "0.2.55.post0.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
