
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-17T09:46:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc5d3f5d76c578b05032017c067ecff1449c1acc",
 "version": "0.9.6.dev20221222"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
