
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-20T22:36:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "055f537cc6045e7b71d1fbac0d9cb07f1efeea40",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
