
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T10:58:45+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea183a36aa42575600e22360a2b7d4a0af7ab4e6",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
