
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-22T07:34:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "629b5e1daf8d58cf70d50c2ac3342ab9c2cb8e2e",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
