
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-22T18:08:34+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "f27bc3bed2bdbb3dfd72fdbfa59a7607d74123a7",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
