
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T15:25:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f240b48d69e9df80aab2cd0aa1619657af5b059",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
