# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['xsstrike', 'xsstrike.core', 'xsstrike.modes', 'xsstrike.plugins']

package_data = \
{'': ['*'], 'xsstrike': ['db/*']}

install_requires = \
['fuzzywuzzy', 'requests', 'tld']

entry_points = \
{'console_scripts': ['xsstrike = xsstrike.xsstrikesback:main']}

setup_kwargs = {
    'name': 'xsstrike',
    'version': '3.2.2',
    'description': 'XSStrike is a Cross Site Scripting detection suite equipped with four hand written parsers, an intelligent payload generator, a powerful fuzzing engine and an incredibly fast crawler. Instead of injecting payloads and checking it works like all the other tools do, XSStrike analyses the response with multiple parsers and then crafts payloads that are guaranteed to work by context analysis integrated with a fuzzing engine.',
    'long_description': '<h1 align="center">\n  <br>\n  <a href="https://github.com/s0md3v/XSStrike"><img src="https://image.ibb.co/cpuYoA/xsstrike-logo.png" alt="XSStrike"></a>\n  <br>\n  XSStrike\n  <br>\n</h1>\n\n<h4 align="center">Advanced XSS Detection Suite</h4>\n\n<p align="center">\n  <a href="https://github.com/s0md3v/XSStrike/releases">\n    <img src="https://img.shields.io/github/release/s0md3v/XSStrike.svg">\n  </a>\n  <a href="https://travis-ci.com/s0md3v/XSStrike">\n    <img src="https://img.shields.io/travis/com/s0md3v/XSStrike.svg">\n  </a>\n  <a href="https://github.com/s0md3v/XSStrike/issues?q=is%3Aissue+is%3Aclosed">\n      <img src="https://img.shields.io/github/issues-closed-raw/s0md3v/XSStrike.svg">\n  </a>\n</p>\n\n![multi xss](https://image.ibb.co/gOCV5L/Screenshot-2018-11-19-13-33-49.png)\n\n<p align="center">\n  <a href="https://github.com/s0md3v/XSStrike/wiki">XSStrike Wiki</a> •\n  <a href="https://github.com/s0md3v/XSStrike/wiki/Usage">Usage</a> •\n  <a href="https://github.com/s0md3v/XSStrike/wiki/FAQ">FAQ</a> •\n  <a href="https://github.com/s0md3v/XSStrike/wiki/For-Developers">For Developers</a> •\n  <a href="https://github.com/s0md3v/XSStrike/wiki/Compatibility-&-Dependencies">Compatibility</a> •\n  <a href="https://github.com/s0md3v/XSStrike#gallery">Gallery</a>\n</p>\n\nXSStrike is a Cross Site Scripting detection suite equipped with four hand written parsers, an intelligent payload generator, a powerful fuzzing engine and an incredibly fast crawler.\n\nInstead of injecting payloads and checking it works like all the other tools do, XSStrike analyses the response with multiple parsers and then crafts payloads that are guaranteed to work by context analysis integrated with a fuzzing engine.\nHere are some examples of the payloads generated by XSStrike:\n```\n}]};(confirm)()//\\\n<A%0aONMouseOvER%0d=%0d[8].find(confirm)>z\n</tiTlE/><a%0donpOintErentER%0d=%0d(prompt)``>z\n</SCRiPT/><DETAILs/+/onpoINTERenTEr%0a=%0aa=prompt,a()//\n```\nApart from that, XSStrike has crawling, fuzzing, parameter discovery, WAF detection capabilities as well. It also scans for DOM XSS vulnerabilities.\n\n### Main Features\n- Reflected and DOM XSS scanning\n- Multi-threaded crawling\n- Context analysis\n- Configurable core\n- WAF detection & evasion\n- Outdated JS lib scanning\n- Intelligent payload generator\n- Handmade HTML & JavaScript parser\n- Powerful fuzzing engine\n- Blind XSS support\n- Highly researched work-flow\n- Complete HTTP support\n- Bruteforce payloads from a file\n- Powered by [Photon](https://github.com/s0md3v/Photon), [Zetanize](https://github.com/s0md3v/zetanize) and [Arjun](https://github.com/s0md3v/Arjun)\n- Payload Encoding\n\n### Documentation\n- [Usage](https://github.com/s0md3v/XSStrike/wiki/Usage)\n- [Compatibility & Dependencies](https://github.com/s0md3v/XSStrike/wiki/Compatibility-&-Dependencies)\n\n### FAQ\n- [It says fuzzywuzzy isn\'t installed but it is.](https://github.com/s0md3v/XSStrike/wiki/FAQ#it-says-fuzzywuzzy-is-not-installed-but-its)\n- [What\'s up with Blind XSS?](https://github.com/s0md3v/XSStrike/wiki/FAQ#whats-up-with-blind-xss)\n- [Why XSStrike boasts that it is the most advanced XSS detection suite?](https://github.com/s0md3v/XSStrike/wiki/FAQ#why-xsstrike-boasts-that-it-is-the-most-advanced-xss-detection-suite)\n- [I like the project, what enhancements and features I can expect in future?](https://github.com/s0md3v/XSStrike/wiki/FAQ#i-like-the-project-what-enhancements-and-features-i-can-expect-in-future)\n- [What\'s the false positive/negative rate?](https://github.com/s0md3v/XSStrike/wiki/FAQ#whats-the-false-positivenegative-rate)\n- [Tool xyz works against the target, while XSStrike doesn\'t!](https://github.com/s0md3v/XSStrike/wiki/FAQ#tool-xyz-works-against-the-target-while-xsstrike-doesnt)\n- [Can I copy it\'s code?](https://github.com/s0md3v/XSStrike/wiki/FAQ#can-i-copy-its-code)\n- [What if I want to embed it into a proprietary software?](https://github.com/s0md3v/XSStrike/wiki/FAQ#what-if-i-want-to-embed-it-into-a-proprietary-software)\n\n### Gallery\n#### DOM XSS\n![dom xss](https://image.ibb.co/bQaQ5L/Screenshot-2018-11-19-13-48-19.png)\n#### Reflected XSS\n![multi xss](https://image.ibb.co/gJogUf/Screenshot-2018-11-19-14-19-36.png)\n#### Crawling\n![crawling](https://image.ibb.co/e6Rezf/Screenshot-2018-11-19-13-50-59.png)\n#### Fuzzing\n![fuzzing](https://image.ibb.co/fnhuFL/Screenshot-2018-11-19-14-04-46.png)\n#### Bruteforcing payloads from a file\n![bruteforcing](https://image.ibb.co/dy5EFL/Screenshot-2018-11-19-14-08-36.png)\n#### Interactive HTTP Headers Prompt\n![headers](https://image.ibb.co/ecNph0/Screenshot-2018-11-19-14-29-35.png)\n#### Hidden Parameter Discovery\n![arjun](https://image.ibb.co/effjh0/Screenshot-2018-11-19-14-16-51.png)\n\n### Contribution, Credits & License\nWays to contribute\n- Suggest a feature\n- Report a bug\n- Fix something and open a pull request\n- Help me document the code\n- Spread the word\n\nLicensed under the GNU GPLv3, see [LICENSE](LICENSE) for more information.\n\nThe WAF signatures in `/db/wafSignatures.json` are taken & modified from [sqlmap](https://github.com/sqlmapproject/sqlmap). I extracted them from sqlmap\'s waf detection modules which can found [here](https://github.com/sqlmapproject/sqlmap/blob/master/waf/) and converted them to JSON.\\\n`/plugins/retireJS.py` is a modified version of [retirejslib](https://github.com/FallibleInc/retirejslib/).\n',
    'author': 'Somdev Sangwan',
    'author_email': 's0md3v@gmail.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/rasheed-rd/XSStrike',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
