# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from openapi_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from openapi_client.model.audiences_sub_object import AudiencesSubObject
from openapi_client.model.campaign_clone_query import CampaignCloneQuery
from openapi_client.model.campaign_clone_query_as_sub_resource import CampaignCloneQueryAsSubResource
from openapi_client.model.campaign_clone_query_as_sub_resource_attributes import CampaignCloneQueryAsSubResourceAttributes
from openapi_client.model.campaign_create_query import CampaignCreateQuery
from openapi_client.model.campaign_create_query_as_sub_resource import CampaignCreateQueryAsSubResource
from openapi_client.model.campaign_create_query_as_sub_resource_attributes import CampaignCreateQueryAsSubResourceAttributes
from openapi_client.model.campaign_message_assign_template_query import CampaignMessageAssignTemplateQuery
from openapi_client.model.campaign_message_assign_template_query_as_sub_resource import CampaignMessageAssignTemplateQueryAsSubResource
from openapi_client.model.campaign_message_assign_template_query_as_sub_resource_attributes import CampaignMessageAssignTemplateQueryAsSubResourceAttributes
from openapi_client.model.campaign_message_partial_update_query import CampaignMessagePartialUpdateQuery
from openapi_client.model.campaign_message_partial_update_query_as_sub_resource import CampaignMessagePartialUpdateQueryAsSubResource
from openapi_client.model.campaign_message_partial_update_query_as_sub_resource_attributes import CampaignMessagePartialUpdateQueryAsSubResourceAttributes
from openapi_client.model.campaign_partial_update_query import CampaignPartialUpdateQuery
from openapi_client.model.campaign_partial_update_query_as_sub_resource import CampaignPartialUpdateQueryAsSubResource
from openapi_client.model.campaign_partial_update_query_as_sub_resource_attributes import CampaignPartialUpdateQueryAsSubResourceAttributes
from openapi_client.model.campaign_send_job_create_query import CampaignSendJobCreateQuery
from openapi_client.model.campaign_send_job_create_query_as_sub_resource import CampaignSendJobCreateQueryAsSubResource
from openapi_client.model.campaign_send_job_create_query_as_sub_resource_attributes import CampaignSendJobCreateQueryAsSubResourceAttributes
from openapi_client.model.campaign_send_job_partial_update_query import CampaignSendJobPartialUpdateQuery
from openapi_client.model.campaign_send_job_partial_update_query_as_sub_resource import CampaignSendJobPartialUpdateQueryAsSubResource
from openapi_client.model.campaign_send_job_partial_update_query_as_sub_resource_attributes import CampaignSendJobPartialUpdateQueryAsSubResourceAttributes
from openapi_client.model.content_sub_object import ContentSubObject
from openapi_client.model.data_privacy_create_deletion_job_query import DataPrivacyCreateDeletionJobQuery
from openapi_client.model.data_privacy_create_deletion_job_query_as_sub_resource import DataPrivacyCreateDeletionJobQueryAsSubResource
from openapi_client.model.data_privacy_create_deletion_job_query_as_sub_resource_attributes import DataPrivacyCreateDeletionJobQueryAsSubResourceAttributes
from openapi_client.model.get_campaigns4_xx_response import GetCampaigns4XXResponse
from openapi_client.model.get_campaigns4_xx_response_errors_inner import GetCampaigns4XXResponseErrorsInner
from openapi_client.model.get_campaigns4_xx_response_errors_inner_source import GetCampaigns4XXResponseErrorsInnerSource
from openapi_client.model.included_profile import IncludedProfile
from openapi_client.model.included_profile_attributes import IncludedProfileAttributes
from openapi_client.model.included_tags import IncludedTags
from openapi_client.model.included_tags_links import IncludedTagsLinks
from openapi_client.model.profile_location import ProfileLocation
from openapi_client.model.profile_location_latitude import ProfileLocationLatitude
from openapi_client.model.send_options_sub_object import SendOptionsSubObject
from openapi_client.model.send_strategy_sub_object import SendStrategySubObject
from openapi_client.model.send_time_sub_object import SendTimeSubObject
from openapi_client.model.static_schedule_options import StaticScheduleOptions
from openapi_client.model.tag_create_query import TagCreateQuery
from openapi_client.model.tag_create_query_as_sub_resource import TagCreateQueryAsSubResource
from openapi_client.model.tag_create_query_as_sub_resource_attributes import TagCreateQueryAsSubResourceAttributes
from openapi_client.model.tag_group_create_query import TagGroupCreateQuery
from openapi_client.model.tag_group_create_query_as_sub_resource import TagGroupCreateQueryAsSubResource
from openapi_client.model.tag_group_create_query_as_sub_resource_attributes import TagGroupCreateQueryAsSubResourceAttributes
from openapi_client.model.tag_group_update_query import TagGroupUpdateQuery
from openapi_client.model.tag_group_update_query_as_sub_resource import TagGroupUpdateQueryAsSubResource
from openapi_client.model.tag_group_update_query_as_sub_resource_attributes import TagGroupUpdateQueryAsSubResourceAttributes
from openapi_client.model.tag_segment_op import TagSegmentOp
from openapi_client.model.tag_segment_op_data_inner import TagSegmentOpDataInner
from openapi_client.model.tag_update_query import TagUpdateQuery
from openapi_client.model.tag_update_query_as_sub_resource import TagUpdateQueryAsSubResource
from openapi_client.model.tag_update_query_as_sub_resource_attributes import TagUpdateQueryAsSubResourceAttributes
from openapi_client.model.template_clone_query_as_sub_resource import TemplateCloneQueryAsSubResource
from openapi_client.model.throttled_schedule_options import ThrottledScheduleOptions
from openapi_client.model.tracking_options_sub_object import TrackingOptionsSubObject
from openapi_client.model.utm_params_sub_object import UTMParamsSubObject
from openapi_client.model.v2_template_render_query_as_sub_resource import V2TemplateRenderQueryAsSubResource
