
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-16T14:29:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "07be81fe80fb9a317b262ebdd518ed75f87d91be",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
