
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-20T10:17:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4246f6a7ce546f118a07323244b2447c198d3107",
 "version": "1.13.83"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
