
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-22T23:24:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "78bbb4a4767516cf6c828a9a79706ce770e1b912",
 "version": "0.2.58.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
