# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _MontagePython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkTileConfigurationPython
else:
    import _itkTileConfigurationPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkTileConfigurationPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkTileConfigurationPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import collections.abc
import itk.itkPointPython
import itk.itkVectorPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_vector_refPython
import itk.itkFixedArrayPython
import itk.itkSizePython
class itkTile2(object):
    r"""Proxy of C++ itkTile2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GetPosition = _swig_new_instance_method(_itkTileConfigurationPython.itkTile2_GetPosition)
    SetPosition = _swig_new_instance_method(_itkTileConfigurationPython.itkTile2_SetPosition)
    GetFileName = _swig_new_instance_method(_itkTileConfigurationPython.itkTile2_GetFileName)
    SetFileName = _swig_new_instance_method(_itkTileConfigurationPython.itkTile2_SetFileName)
    __swig_destroy__ = _itkTileConfigurationPython.delete_itkTile2

    def __init__(self, *args):
        r"""
        __init__(self, arg0) -> itkTile2

        Parameters
        ----------
        arg0: itkTile2 const &

        __init__(self) -> itkTile2
        """
        _itkTileConfigurationPython.itkTile2_swiginit(self, _itkTileConfigurationPython.new_itkTile2(*args))

# Register itkTile2 in _itkTileConfigurationPython:
_itkTileConfigurationPython.itkTile2_swigregister(itkTile2)

class itkTile3(object):
    r"""Proxy of C++ itkTile3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GetPosition = _swig_new_instance_method(_itkTileConfigurationPython.itkTile3_GetPosition)
    SetPosition = _swig_new_instance_method(_itkTileConfigurationPython.itkTile3_SetPosition)
    GetFileName = _swig_new_instance_method(_itkTileConfigurationPython.itkTile3_GetFileName)
    SetFileName = _swig_new_instance_method(_itkTileConfigurationPython.itkTile3_SetFileName)
    __swig_destroy__ = _itkTileConfigurationPython.delete_itkTile3

    def __init__(self, *args):
        r"""
        __init__(self, arg0) -> itkTile3

        Parameters
        ----------
        arg0: itkTile3 const &

        __init__(self) -> itkTile3
        """
        _itkTileConfigurationPython.itkTile3_swiginit(self, _itkTileConfigurationPython.new_itkTile3(*args))

# Register itkTile3 in _itkTileConfigurationPython:
_itkTileConfigurationPython.itkTile3_swigregister(itkTile3)

class itkTile4(object):
    r"""Proxy of C++ itkTile4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GetPosition = _swig_new_instance_method(_itkTileConfigurationPython.itkTile4_GetPosition)
    SetPosition = _swig_new_instance_method(_itkTileConfigurationPython.itkTile4_SetPosition)
    GetFileName = _swig_new_instance_method(_itkTileConfigurationPython.itkTile4_GetFileName)
    SetFileName = _swig_new_instance_method(_itkTileConfigurationPython.itkTile4_SetFileName)
    __swig_destroy__ = _itkTileConfigurationPython.delete_itkTile4

    def __init__(self, *args):
        r"""
        __init__(self, arg0) -> itkTile4

        Parameters
        ----------
        arg0: itkTile4 const &

        __init__(self) -> itkTile4
        """
        _itkTileConfigurationPython.itkTile4_swiginit(self, _itkTileConfigurationPython.new_itkTile4(*args))

# Register itkTile4 in _itkTileConfigurationPython:
_itkTileConfigurationPython.itkTile4_swigregister(itkTile4)

class itkTileConfiguration2(object):
    r"""Proxy of C++ itkTileConfiguration2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GetAxisSizes = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_GetAxisSizes)
    SetAxisSizes = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_SetAxisSizes)
    GetTile = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_GetTile)
    SetTile = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_SetTile)
    LinearSize = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_LinearSize)
    nDIndexToLinearIndex = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_nDIndexToLinearIndex)
    LinearIndexToNDIndex = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_LinearIndexToNDIndex)
    TryParse = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration2_TryParse)
    Parse = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_Parse)
    Write = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration2_Write)
    getNextNonCommentLine = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration2_getNextNonCommentLine)
    parseLine = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration2_parseLine)
    __swig_destroy__ = _itkTileConfigurationPython.delete_itkTileConfiguration2

    def __init__(self, *args):
        r"""
        __init__(self, arg0) -> itkTileConfiguration2

        Parameters
        ----------
        arg0: itkTileConfiguration2 const &

        __init__(self) -> itkTileConfiguration2
        """
        _itkTileConfigurationPython.itkTileConfiguration2_swiginit(self, _itkTileConfigurationPython.new_itkTileConfiguration2(*args))

# Register itkTileConfiguration2 in _itkTileConfigurationPython:
_itkTileConfigurationPython.itkTileConfiguration2_swigregister(itkTileConfiguration2)
itkTileConfiguration2_TryParse = _itkTileConfigurationPython.itkTileConfiguration2_TryParse
itkTileConfiguration2_getNextNonCommentLine = _itkTileConfigurationPython.itkTileConfiguration2_getNextNonCommentLine
itkTileConfiguration2_parseLine = _itkTileConfigurationPython.itkTileConfiguration2_parseLine

class itkTileConfiguration3(object):
    r"""Proxy of C++ itkTileConfiguration3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GetAxisSizes = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_GetAxisSizes)
    SetAxisSizes = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_SetAxisSizes)
    GetTile = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_GetTile)
    SetTile = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_SetTile)
    LinearSize = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_LinearSize)
    nDIndexToLinearIndex = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_nDIndexToLinearIndex)
    LinearIndexToNDIndex = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_LinearIndexToNDIndex)
    TryParse = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration3_TryParse)
    Parse = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_Parse)
    Write = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration3_Write)
    getNextNonCommentLine = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration3_getNextNonCommentLine)
    parseLine = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration3_parseLine)
    __swig_destroy__ = _itkTileConfigurationPython.delete_itkTileConfiguration3

    def __init__(self, *args):
        r"""
        __init__(self, arg0) -> itkTileConfiguration3

        Parameters
        ----------
        arg0: itkTileConfiguration3 const &

        __init__(self) -> itkTileConfiguration3
        """
        _itkTileConfigurationPython.itkTileConfiguration3_swiginit(self, _itkTileConfigurationPython.new_itkTileConfiguration3(*args))

# Register itkTileConfiguration3 in _itkTileConfigurationPython:
_itkTileConfigurationPython.itkTileConfiguration3_swigregister(itkTileConfiguration3)
itkTileConfiguration3_TryParse = _itkTileConfigurationPython.itkTileConfiguration3_TryParse
itkTileConfiguration3_getNextNonCommentLine = _itkTileConfigurationPython.itkTileConfiguration3_getNextNonCommentLine
itkTileConfiguration3_parseLine = _itkTileConfigurationPython.itkTileConfiguration3_parseLine

class itkTileConfiguration4(object):
    r"""Proxy of C++ itkTileConfiguration4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    GetAxisSizes = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_GetAxisSizes)
    SetAxisSizes = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_SetAxisSizes)
    GetTile = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_GetTile)
    SetTile = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_SetTile)
    LinearSize = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_LinearSize)
    nDIndexToLinearIndex = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_nDIndexToLinearIndex)
    LinearIndexToNDIndex = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_LinearIndexToNDIndex)
    TryParse = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration4_TryParse)
    Parse = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_Parse)
    Write = _swig_new_instance_method(_itkTileConfigurationPython.itkTileConfiguration4_Write)
    getNextNonCommentLine = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration4_getNextNonCommentLine)
    parseLine = _swig_new_static_method(_itkTileConfigurationPython.itkTileConfiguration4_parseLine)
    __swig_destroy__ = _itkTileConfigurationPython.delete_itkTileConfiguration4

    def __init__(self, *args):
        r"""
        __init__(self, arg0) -> itkTileConfiguration4

        Parameters
        ----------
        arg0: itkTileConfiguration4 const &

        __init__(self) -> itkTileConfiguration4
        """
        _itkTileConfigurationPython.itkTileConfiguration4_swiginit(self, _itkTileConfigurationPython.new_itkTileConfiguration4(*args))

# Register itkTileConfiguration4 in _itkTileConfigurationPython:
_itkTileConfigurationPython.itkTileConfiguration4_swigregister(itkTileConfiguration4)
itkTileConfiguration4_TryParse = _itkTileConfigurationPython.itkTileConfiguration4_TryParse
itkTileConfiguration4_getNextNonCommentLine = _itkTileConfigurationPython.itkTileConfiguration4_getNextNonCommentLine
itkTileConfiguration4_parseLine = _itkTileConfigurationPython.itkTileConfiguration4_parseLine



