
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T15:17:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5611bf714a33c1588f83841280a48a3709e6d8b",
 "version": "0.2.55.post0.dev50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
