
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T16:06:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e76108519c18419e6e88e70f7b8fa528a16e3b65",
 "version": "0.1.59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
