class data:
    def __init__(self,data):
        self.data=data
    def read(self):
        return self.data
    def encodeData(self):
        data=self.data
        data=data.lower()
        data=data.replace("a","{0}")
        data=data.replace("b","{1}")
        data=data.replace("c","{2}")
        data=data.replace("d","{3}")
        data=data.replace("e","{4}")
        data=data.replace("f","{5}")
        data=data.replace("g","{6}")
        data=data.replace("h","{7}")
        data=data.replace("i","{8}")
        data=data.replace("j","{9}")
        data=data.replace("k","{10}")
        data=data.replace("l","{11}")
        data=data.replace("m","{12}")
        data=data.replace("n","{13}")
        data=data.replace("o","{14}")
        data=data.replace("p","{15}")
        data=data.replace("q","{16}")
        data=data.replace("r","{17}")
        data=data.replace("s","{18}")
        data=data.replace("t","{19}")
        data=data.replace("u","{20}")
        data=data.replace("v","{21}")
        data=data.replace("w","{22}")
        data=data.replace("x","{23}")
        data=data.replace("y","{24}")
        data=data.replace("z","{25}")
        self.data=data
    def decodeData(self):
            data=self.data
            data=data.replace("{0}","a")
            data=data.replace("{1}","b")
            data=data.replace("{2}","c")
            data=data.replace("{3}","d")
            data=data.replace("{4}","e")
            data=data.replace("{5}","f")
            data=data.replace("{6}","g")
            data=data.replace("{7}","h")
            data=data.replace("{8}","i")
            data=data.replace("{9}","j")
            data=data.replace("{10}","k")
            data=data.replace("{11}","l")
            data=data.replace("{12}","m")
            data=data.replace("{13}","n")
            data=data.replace("{14}","o")
            data=data.replace("{15}","p")
            data=data.replace("{16}","q")
            data=data.replace("{17}","r")
            data=data.replace("{18}","s")
            data=data.replace("{19}","t")
            data=data.replace("{20}","u")
            data=data.replace("{21}","v")
            data=data.replace("{22}","w")
            data=data.replace("{23}","x")
            data=data.replace("{24}","y")
            data=data.replace("{25}","z")
            self.data=data
