# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['webpack_boilerplate',
 'webpack_boilerplate.contrib',
 'webpack_boilerplate.frontend_template.hooks',
 'webpack_boilerplate.management',
 'webpack_boilerplate.management.commands',
 'webpack_boilerplate.templatetags']

package_data = \
{'': ['*'],
 'webpack_boilerplate': ['frontend_template/cookiecutter.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.babelrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.browserslistrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.eslintrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.gitignore',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.nvmrc',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/.stylelintrc.json',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/README.md',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package-lock.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/package.json',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/postcss.config.js',
                         'frontend_template/{{cookiecutter.project_slug}}/src/application/*',
                         'frontend_template/{{cookiecutter.project_slug}}/src/components/*',
                         'frontend_template/{{cookiecutter.project_slug}}/src/styles/*',
                         'frontend_template/{{cookiecutter.project_slug}}/vendors/*',
                         'frontend_template/{{cookiecutter.project_slug}}/vendors/images/*',
                         'frontend_template/{{cookiecutter.project_slug}}/webpack/*']}

install_requires = \
['cookiecutter>=1.7.0']

setup_kwargs = {
    'name': 'python-webpack-boilerplate',
    'version': '1.0.1',
    'description': 'Jump start frontend project bundled by Webpack',
    'long_description': '# Jump start frontend project bundled by Webpack\n\n[![Build Status](https://github.com/AccordBox/python-webpack-boilerplate/actions/workflows/ci.yml/badge.svg?branch=master)](https://github.com/AccordBox/python-webpack-boilerplate/actions/workflows/ci.yml)\n[![PyPI version](https://badge.fury.io/py/python-webpack-boilerplate.svg)](https://badge.fury.io/py/python-webpack-boilerplate)\n[![Documentation](https://img.shields.io/badge/Documentation-link-green.svg)](https://python-webpack-boilerplate.rtfd.io/)\n\n## Difference between django-webpack-loader\n\nWhen using `django-webpack-loader`, you need to create `Webpack` project on your own, which is not easy for many newbie Django developers.\n\n`python-webpack-boilerplate` can let you play with modern frontend tech in Django, even you have no idea how to config Webpack.\n\n## Features\n\n- **Supports Django and Flask** (will support more framework in the future)\n- Automatic multiple entry points\n- Automatic code splitting\n- Hot Module Replacement (HMR) (auto reload web page if you edit JS or SCSS)\n- Easy to config and customize\n- ES6 Support via [babel](https://babeljs.io/) (v7)\n- JavaScript Linting via [eslint](https://eslint.org/)\n- SCSS Support via [sass-loader](https://github.com/jtangelder/sass-loader)\n- Autoprefixing of browserspecific CSS rules via [postcss](https://postcss.org/) and [postcss-preset-env](https://github.com/csstools/postcss-preset-env)\n- Style Linting via [stylelint](https://stylelint.io/)\n\n## Documentation\n\n1. [Setup With Django](https://python-webpack-boilerplate.readthedocs.io/en/latest/setup_with_django/)\n1. [Setup With Flask](https://python-webpack-boilerplate.readthedocs.io/en/latest/setup_with_flask/)\n1. [Frontend Workflow](https://python-webpack-boilerplate.readthedocs.io/en/latest/frontend/)\n\n## Special Thanks\n\n* [Definitive Guide to Django and Webpack](https://www.accordbox.com/blog/definitive-guide-django-and-webpack/)\n* [django-webpack-loader](https://github.com/owais/django-webpack-loader)\n* [rails/webpacker](https://github.com/rails/webpacker)\n* [wbkd/webpack-starter](https://github.com/wbkd/webpack-starter)\n',
    'author': 'Michael Yin',
    'author_email': 'michaelyin@accordbox.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/AccordBox/python-webpack-boilerplate',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)
