
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-20T13:44:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dec6191ac300bb2958dc26d620ead35eb4940e98",
 "version": "0.2.57.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
