
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T15:40:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f677bdb71f4e34424e187ae603af6a5399575b0b",
 "version": "2.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
