
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T10:24:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4d3227a5481a5fbaa7c95be95b8a33606a62b0c",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
