
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-24T10:39:35-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a69b18e107f7f44f324222f9be176afb8bdd4ac8",
 "version": "2.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
