
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T21:18:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "859aac4b5b94fd5fe8572f3752777658d4b8c8c6",
 "version": "1.0.13.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
