"""Code of the project py-linq-sql."""

__version__ = "1.6.1-pre-release"

# Local imports
from .build_request.consult_aggregate import avg  # noqa: F401
from .build_request.consult_aggregate import concat  # noqa: F401
from .build_request.consult_aggregate import count  # noqa: F401
from .build_request.consult_aggregate import max  # noqa: F401
from .build_request.consult_aggregate import min  # noqa: F401
from .build_request.consult_aggregate import sum  # noqa: F401
from .exception.exception import ActionError  # noqa: F401
from .exception.exception import AlreadyExecutedError  # noqa: F401
from .exception.exception import AlterError  # noqa: F401
from .exception.exception import ColumnNameError  # noqa: F401
from .exception.exception import CursorCloseError  # noqa: F401
from .exception.exception import DatabError  # noqa: F401
from .exception.exception import DeleteError  # noqa: F401
from .exception.exception import EmptyInputError  # noqa: F401
from .exception.exception import EmptyQueryError  # noqa: F401
from .exception.exception import EmptyRecordError  # noqa: F401
from .exception.exception import ExecutionError  # noqa: F401
from .exception.exception import FetchError  # noqa: F401
from .exception.exception import GroupByWithJoinError  # noqa: F401
from .exception.exception import LengthMismatchError  # noqa: F401
from .exception.exception import MoreThanZeroError  # noqa: F401
from .exception.exception import NeedSelectError  # noqa: F401
from .exception.exception import NeedWhereError  # noqa: F401
from .exception.exception import NegativeNumberError  # noqa: F401
from .exception.exception import NoMaxOrMinAfterLimitOffsetError  # noqa: F401
from .exception.exception import OneError  # noqa: F401
from .exception.exception import OtherThanWhereError  # noqa: F401
from .exception.exception import PSQLConnectionError  # noqa: F401
from .exception.exception import PyLinqSQLError  # noqa: F401
from .exception.exception import ReadOnlyPermissionDeniedError  # noqa: F401
from .exception.exception import ReturnEmptyEnumerable  # noqa: F401
from .exception.exception import SelectError  # noqa: F401
from .exception.exception import TableError  # noqa: F401
from .exception.exception import TablePermissionDeniedError  # noqa: F401
from .exception.exception import TerminalError  # noqa: F401
from .exception.exception import TooManyReturnValueError  # noqa: F401
from .exception.exception import TypeOperatorError  # noqa: F401
from .exception.exception import UnknownCommandTypeError  # noqa: F401
from .sql_enumerable.sql_enumerable import SQLEnumerable  # noqa: F401
from .utils.classes.enum import JoinType  # noqa: F401
from .utils.classes.other_classes import PyLinqSqlInsertType  # noqa: F401
from .utils.db import connect  # noqa: F401
from .utils.execute import logg  # noqa: F401
from .utils.functions.magic_dp_hyperb_functions import acosh  # noqa: F401
from .utils.functions.magic_dp_hyperb_functions import asinh  # noqa: F401
from .utils.functions.magic_dp_hyperb_functions import atanh  # noqa: F401
from .utils.functions.magic_dp_hyperb_functions import cosh  # noqa: F401
from .utils.functions.magic_dp_hyperb_functions import sinh  # noqa: F401
from .utils.functions.magic_dp_hyperb_functions import tanh  # noqa: F401
from .utils.functions.magic_dp_maths_functions import cbrt  # noqa: F401
from .utils.functions.magic_dp_maths_functions import ceil  # noqa: F401
from .utils.functions.magic_dp_maths_functions import degrees  # noqa: F401
from .utils.functions.magic_dp_maths_functions import exp  # noqa: F401
from .utils.functions.magic_dp_maths_functions import factorial  # noqa: F401
from .utils.functions.magic_dp_maths_functions import floor  # noqa: F401
from .utils.functions.magic_dp_maths_functions import gcd  # noqa: F401
from .utils.functions.magic_dp_maths_functions import lcm  # noqa: F401
from .utils.functions.magic_dp_maths_functions import ln  # noqa: F401
from .utils.functions.magic_dp_maths_functions import log  # noqa: F401
from .utils.functions.magic_dp_maths_functions import log10  # noqa: F401
from .utils.functions.magic_dp_maths_functions import min_scale  # noqa: F401
from .utils.functions.magic_dp_maths_functions import radians  # noqa: F401
from .utils.functions.magic_dp_maths_functions import round  # noqa: F401
from .utils.functions.magic_dp_maths_functions import scale  # noqa: F401
from .utils.functions.magic_dp_maths_functions import sign  # noqa: F401
from .utils.functions.magic_dp_maths_functions import sqrt  # noqa: F401
from .utils.functions.magic_dp_maths_functions import trim_scale  # noqa: F401
from .utils.functions.magic_dp_maths_functions import trunc  # noqa: F401
from .utils.functions.magic_dp_str_functions import lower, title, upper  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import acos  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import acosd  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import asin  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import asind  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import atan  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import atan2  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import atan2d  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import atand  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import cos  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import cosd  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import cot  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import cotd  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import sin  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import sind  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import tan  # noqa: F401
from .utils.functions.magic_dp_trigo_functions import tand  # noqa: F401
from .utils.functions.other_functions import pretty_print  # noqa: F401
