
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-20T15:47:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e52ed4aed6aa9dd9641e2de5a5e8e4c95f554b27",
 "version": "2.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
