
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-23T16:33:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd6f7f5bdef5321b6ce54927d7dd50c6855a24d5",
 "version": "0.2.58.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
