
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-20T13:25:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "02c3dc54766c85f1105aded589da07d4ba150103",
 "version": "0.2.57"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
