# Generated by Django 3.2.12 on 2022-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_reports_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentdata',
            options={'verbose_name_plural': 'Reports device serial number and model'},
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='error',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
