# Generated by Django 3.2.12 on 2022-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_reports_plugin', '0002_auto_20221208_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentdata',
            options={'verbose_name_plural': 'Инвентаризация'},
        ),
    ]
