# Generated by Django 3.2.12 on 2022-12-21 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0053_asn_model'),
        ('dcim', '0144_fix_cable_abs_length'),
        ('netbox_reports_plugin', '0003_alter_equipmentdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdata',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_set_reports', to='dcim.region'),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices_set_reports', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_set_reports', to='ipam.ipaddress'),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_set_reports', to='dcim.manufacturer'),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_set_reports', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_set_reports', to='dcim.region'),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_set_reports', to='dcim.site'),
        ),
    ]
