
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T17:15:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "56c2455df7fb0e5a61aa0cc010c73ca3bdec1007",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
