from dscore.disEMBL import get_disEMBL


seq = 'MTKKSTKAPAKKAAPAAKAAPAAKRGAAADSGKVAKTQLVEMVADQTGLTKKQSEEAISSMLECVVSALQSGKSVGLPGLGTLSVKETAARTGVRPGTSEKIQIPAGKKVAFKVASTLKGNL'


def test_disEMBL():
    data = get_disEMBL(seq)
