
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-23T18:35:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fd7e88ed3b46a202235ae46ceb77479232b4739",
 "version": "0.2.58.post0.dev21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
