# Generated by Django 2.2.13 on 2020-07-01 23:17

from django.db import migrations, models
from api_key.utils import get_random_str

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('api_secret', models.CharField(default=get_random_str, max_length=128)),
                ('endpoint', models.URLField(blank=True, help_text='if not provided, all api is allowed')),
                ('source', models.GenericIPAddressField(blank=True, help_text='if not provided, all source ip is allowed', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='valid permanently if empty', null=True)),
                ('description', models.TextField(blank=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
