# Generated by Django 2.2 on 2020-10-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='apikey',
            name='timeout_in',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='source',
            field=models.CharField(blank=True, default='127,192,172', help_text='if not provided, all source ip is allowed', max_length=256),
        ),
    ]
