# Generated by Django 2.2.12 on 2022-02-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0002_auto_20201007_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='timeout_in',
            field=models.PositiveSmallIntegerField(default=60, help_text='set 0 to ignore checking'),
        ),
    ]
