
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-22T10:42:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7340a7a2ba3cc482b4eabc7bf8ea2dc41602e513",
 "version": "2815"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
