
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T17:24:23-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "be53d10d7ee36878f91d97e37e42f8ec4b4551e6",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
