
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T16:13:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "59e5398a4346a8a698120b32af802dea438bea6a",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
