
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-19T17:14:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ab0201e26390c3e773398f3cadac4b2ed8c1e6f",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
