
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T17:40:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a11834e30c2bc1ce971e7d4d410deb20a31bd650",
 "version": "0.1.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
