
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-25T02:22:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "49f534769f256a15f635d0e02540558626c8c35c",
 "version": "0.5.dev2252"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
