print("Calling function __init__ with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/test1.py') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file1.txt') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file2.txt') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file3.txt') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file4.txt') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/__pycache__') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/__pycache__/test1.cpython")
print("-38.pyc') {}")
print("Calling function load_test_files with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/__pycache__/test1.cpython")
print("-39.pyc') {}")
print("Calling function run with arguments (<__main__.Runner object at 0x000001D84C63B610>,) {}")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/test1.py') {}")
print("Calling function load_module with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/test1.py') {}")
print("Running Test test_a1_has_sample Failure")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file1.txt') {}")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file2.txt') {}")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file3.txt') {}")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/textfiles/file4.txt') {}")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/__pycache__/test1.cpython")
print("-38.pyc') {}")
print("Calling function run_single_file with arguments (<__main__.Runner object at 0x000001D84C63B610>, 'C:\\Users\\yash0\\PycharmProjects\\pythonProject\\external_code/__pycache__/test1.cpython")
print("-39.pyc') {}")
print("tests failed")
