
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T19:38:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0959489cf9fd193dbb05a9566e5680ac5f114a39",
 "version": "0.0.50.dev20221223"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
