
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-20T19:23:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "982e4c4202e7c6c1196c59c228fd12903b79d32e",
 "version": "5.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
