# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import time_interval_pb2 as time__interval__pb2
import boundingbox_stamped_pb2 as boundingbox__stamped__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='query.proto',
  package='seerep',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bquery.proto\x12\x06seerep\x1a\x13time_interval.proto\x1a\x19\x62oundingbox_stamped.proto\"\xfb\x01\n\x05Query\x12\x36\n\x12\x62oundingboxStamped\x18\x01 \x01(\x0b\x32\x1a.seerep.BoundingboxStamped\x12*\n\x0ctimeinterval\x18\x02 \x01(\x0b\x32\x14.seerep.TimeInterval\x12\r\n\x05label\x18\x03 \x03(\t\x12\x19\n\x11mustHaveAllLabels\x18\x04 \x01(\x08\x12\x13\n\x0bprojectuuid\x18\x05 \x03(\t\x12\x14\n\x0cinstanceuuid\x18\x06 \x03(\t\x12\x10\n\x08\x64\x61tauuid\x18\x07 \x03(\t\x12\x13\n\x0bwithoutdata\x18\x08 \x01(\x08\x12\x12\n\nmaxNumData\x18\t \x01(\rb\x06proto3'
  ,
  dependencies=[time__interval__pb2.DESCRIPTOR,boundingbox__stamped__pb2.DESCRIPTOR,])




_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='seerep.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundingboxStamped', full_name='seerep.Query.boundingboxStamped', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeinterval', full_name='seerep.Query.timeinterval', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='seerep.Query.label', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mustHaveAllLabels', full_name='seerep.Query.mustHaveAllLabels', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='projectuuid', full_name='seerep.Query.projectuuid', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instanceuuid', full_name='seerep.Query.instanceuuid', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datauuid', full_name='seerep.Query.datauuid', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='withoutdata', full_name='seerep.Query.withoutdata', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxNumData', full_name='seerep.Query.maxNumData', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=323,
)

_QUERY.fields_by_name['boundingboxStamped'].message_type = boundingbox__stamped__pb2._BOUNDINGBOXSTAMPED
_QUERY.fields_by_name['timeinterval'].message_type = time__interval__pb2._TIMEINTERVAL
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:seerep.Query)
  })
_sym_db.RegisterMessage(Query)


# @@protoc_insertion_point(module_scope)
