# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boundingbox_labeled.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import boundingbox_pb2 as boundingbox__pb2
import label_with_instance_pb2 as label__with__instance__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='boundingbox_labeled.proto',
  package='seerep',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x62oundingbox_labeled.proto\x12\x06seerep\x1a\x11\x62oundingbox.proto\x1a\x19label_with_instance.proto\"t\n\x12\x42oundingBoxLabeled\x12\x34\n\x11labelWithInstance\x18\x01 \x01(\x0b\x32\x19.seerep.LabelWithInstance\x12(\n\x0b\x62oundingBox\x18\x02 \x01(\x0b\x32\x13.seerep.Boundingboxb\x06proto3'
  ,
  dependencies=[boundingbox__pb2.DESCRIPTOR,label__with__instance__pb2.DESCRIPTOR,])




_BOUNDINGBOXLABELED = _descriptor.Descriptor(
  name='BoundingBoxLabeled',
  full_name='seerep.BoundingBoxLabeled',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='labelWithInstance', full_name='seerep.BoundingBoxLabeled.labelWithInstance', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boundingBox', full_name='seerep.BoundingBoxLabeled.boundingBox', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=199,
)

_BOUNDINGBOXLABELED.fields_by_name['labelWithInstance'].message_type = label__with__instance__pb2._LABELWITHINSTANCE
_BOUNDINGBOXLABELED.fields_by_name['boundingBox'].message_type = boundingbox__pb2._BOUNDINGBOX
DESCRIPTOR.message_types_by_name['BoundingBoxLabeled'] = _BOUNDINGBOXLABELED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoundingBoxLabeled = _reflection.GeneratedProtocolMessageType('BoundingBoxLabeled', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDINGBOXLABELED,
  '__module__' : 'boundingbox_labeled_pb2'
  # @@protoc_insertion_point(class_scope:seerep.BoundingBoxLabeled)
  })
_sym_db.RegisterMessage(BoundingBoxLabeled)


# @@protoc_insertion_point(module_scope)
