# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twist_with_covariance_stamped.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import twist_with_covariance_pb2 as twist__with__covariance__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='twist_with_covariance_stamped.proto',
  package='seerep',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#twist_with_covariance_stamped.proto\x12\x06seerep\x1a\x0cheader.proto\x1a\x1btwist_with_covariance.proto\"h\n\x1aTwistWithCovarianceStamped\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.seerep.Header\x12*\n\x05twist\x18\x02 \x01(\x0b\x32\x1b.seerep.TwistWithCovarianceb\x06proto3'
  ,
  dependencies=[header__pb2.DESCRIPTOR,twist__with__covariance__pb2.DESCRIPTOR,])




_TWISTWITHCOVARIANCESTAMPED = _descriptor.Descriptor(
  name='TwistWithCovarianceStamped',
  full_name='seerep.TwistWithCovarianceStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='seerep.TwistWithCovarianceStamped.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twist', full_name='seerep.TwistWithCovarianceStamped.twist', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=194,
)

_TWISTWITHCOVARIANCESTAMPED.fields_by_name['header'].message_type = header__pb2._HEADER
_TWISTWITHCOVARIANCESTAMPED.fields_by_name['twist'].message_type = twist__with__covariance__pb2._TWISTWITHCOVARIANCE
DESCRIPTOR.message_types_by_name['TwistWithCovarianceStamped'] = _TWISTWITHCOVARIANCESTAMPED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TwistWithCovarianceStamped = _reflection.GeneratedProtocolMessageType('TwistWithCovarianceStamped', (_message.Message,), {
  'DESCRIPTOR' : _TWISTWITHCOVARIANCESTAMPED,
  '__module__' : 'twist_with_covariance_stamped_pb2'
  # @@protoc_insertion_point(class_scope:seerep.TwistWithCovarianceStamped)
  })
_sym_db.RegisterMessage(TwistWithCovarianceStamped)


# @@protoc_insertion_point(module_scope)
