
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-21T22:43:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a60ea9ffe26cac45dcf3325eb1bc2c7fe5d9805b",
 "version": "0.2.58.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
