
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-22T16:14:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5ad4661d7282729366348f9959829c7e1c2b5fa",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
